name: Rational Integration Tester

on: workflow_dispatch

jobs:
    API-Action:
        name: Rational Integration Tester
        runs-on: self-hosted
        steps:
         - name: Rational Integration Tester
           uses: IBM/devopsauto-integrtest-actions@v1
           with:
            projectDir: C:\Users\preethi.as\ibmapiproject
            parameterFile: addNumbers/addition/Test1
            projectName: ibmapiproject
            environment: BLMYCLDDW161391
            tests: Test1
