name: Rational Integration Tester

on: workflow_dispatch

jobs:
    API-Action:
        name: Rational Integration Tester
        runs-on: self-hosted
        steps:
         - name: Rational Integration Tester
           uses: HCL-TECH-SOFTWARE/onetest-api-action@v1
           with:
            projectDir: C:\Users\preethi.as\
            projectName: NewAPIProject
            environment: BLMYCLDDW161391
            tests: Test1
